[2025-02-17T16:44:19.638+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-17T16:44:19.781+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tax_etl_pipeline.run_tax_etl scheduled__2025-02-17T16:20:00+00:00 [queued]>
[2025-02-17T16:44:19.818+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tax_etl_pipeline.run_tax_etl scheduled__2025-02-17T16:20:00+00:00 [queued]>
[2025-02-17T16:44:19.819+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-02-17T16:44:19.857+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): run_tax_etl> on 2025-02-17 16:20:00+00:00
[2025-02-17T16:44:19.887+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tax_etl_pipeline', 'run_tax_etl', 'scheduled__2025-02-17T16:20:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/tax_etl_dag.py', '--cfg-path', '/tmp/tmp_zcqvo87']
[2025-02-17T16:44:19.897+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask run_tax_etl
[2025-02-17T16:44:19.904+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=262) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-17T16:44:19.907+0000] {standard_task_runner.py:72} INFO - Started process 263 to run task
[2025-02-17T16:44:20.366+0000] {task_command.py:467} INFO - Running <TaskInstance: tax_etl_pipeline.run_tax_etl scheduled__2025-02-17T16:20:00+00:00 [running]> on host 5a3b6838f80f
[2025-02-17T16:44:20.614+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tax_etl_pipeline' AIRFLOW_CTX_TASK_ID='run_tax_etl' AIRFLOW_CTX_EXECUTION_DATE='2025-02-17T16:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-17T16:20:00+00:00'
[2025-02-17T16:44:20.616+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-17T16:44:20.836+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tax_etl_dag.py", line 48, in run_etl
    raise Exception(f"Script failed with error: {result.stderr}")
Exception: Script failed with error: Traceback (most recent call last):
  File "/opt/***/etl/main.py", line 1, in <module>
    from etl.pipelines.tax_pipeline import TaxPipeline
  File "/opt/***/etl/etl/pipelines/tax_pipeline.py", line 1, in <module>
    from etl.extract.extract_txt import ExtractTXT
  File "/opt/***/etl/etl/extract/extract_txt.py", line 1, in <module>
    from etl.extract.extract_base import ExtractBase
  File "/opt/***/etl/etl/extract/extract_base.py", line 1, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'

[2025-02-17T16:44:20.949+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=tax_etl_pipeline, task_id=run_tax_etl, run_id=scheduled__2025-02-17T16:20:00+00:00, execution_date=20250217T162000, start_date=20250217T164419, end_date=20250217T164420
[2025-02-17T16:44:21.065+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-17T16:44:21.066+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 6 for task run_tax_etl (Script failed with error: Traceback (most recent call last):
  File "/opt/***/etl/main.py", line 1, in <module>
    from etl.pipelines.tax_pipeline import TaxPipeline
  File "/opt/***/etl/etl/pipelines/tax_pipeline.py", line 1, in <module>
    from etl.extract.extract_txt import ExtractTXT
  File "/opt/***/etl/etl/extract/extract_txt.py", line 1, in <module>
    from etl.extract.extract_base import ExtractBase
  File "/opt/***/etl/etl/extract/extract_base.py", line 1, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
; 263)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tax_etl_dag.py", line 48, in run_etl
    raise Exception(f"Script failed with error: {result.stderr}")
Exception: Script failed with error: Traceback (most recent call last):
  File "/opt/***/etl/main.py", line 1, in <module>
    from etl.pipelines.tax_pipeline import TaxPipeline
  File "/opt/***/etl/etl/pipelines/tax_pipeline.py", line 1, in <module>
    from etl.extract.extract_txt import ExtractTXT
  File "/opt/***/etl/etl/extract/extract_txt.py", line 1, in <module>
    from etl.extract.extract_base import ExtractBase
  File "/opt/***/etl/etl/extract/extract_base.py", line 1, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'

[2025-02-17T16:44:21.121+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-17T16:44:21.176+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-17T16:44:21.182+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
